
services:
  web:
    build: .
    image: 240317130487.dkr.ecr.ap-northeast-2.amazonaws.com/datespot:${DOCKER_IMAGE_TAG:-latest}
    container_name: datespot
    volumes:
      - /tmp/jenkins_workspace:/code  # Jenkins 디렉터리 대신 임시 디렉터리 사용
    ports:
      - "6004:6004"
    environment: 
      DATESPOT_DB: "3.34.18.250"
      DATESPOT_DB_USER: "datespot"
      DATESPOT_DB_PASSWORD: "qwer1234"
      DATESPOT_DB_TABLE: "datespot"
      DATESPOT_PORT: "3306"
      REDIS_HOST: "redis_host"
      REDIS_PORT: "6379"
      BUCKET_NAME : "datespot-image"
      REGION : "ap-northeast-2"
