name: Deploy to cloudtype
on:
  push:
    branches:
      - main
      - fastapi
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: wylee99/fastapi
          stage: main
          yaml: |
            name: fastapi
            app: python@3.9
            options:
              env:
                - name: AWS_ACCESS_KEY_ID
                  var: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  var: AWS_SECRET_ACCESS_KEY
                - name: BUCKET_NAME
                  var: BUCKET_NAME
                - name: REGION
                  var: REGION
                - name: DATESPOT_DB_USER
                  var: DATESPOT_DB_USER
                - name: DATESPOT_DB_PASSWORD
                  var: DATESPOT_DB_PASSWORD
                - name: DATESPOT_DB_TABLE
                  var: DATESPOT_DB_TABLE
                - name: REDIS_PORT
                  var: REDIS_PORT
              ports: "6004"
              start: uvicorn main:app --host 0.0.0.0 --port 8000
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: python-fastapi