name: Deploy to cloudtype
on:
  push:
    branches:
      - main
      - fastapi
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: wylee99/datespot
          stage: main
          yaml: |
            name: datespot
            app: dockerfile
            options:
              ports: "8000"
              start: uvicorn backend.main:app --host 0.0.0.0 --port 8000
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}